// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw-VZ2LAVKK_CwuBmFtjxpOmH3co08pqo',
    appId: '1:992090844900:web:797d115a971ee3e46b46f1',
    messagingSenderId: '992090844900',
    projectId: 'dashfleet-app-flutter',
    authDomain: 'dashfleet-app-flutter.firebaseapp.com',
    storageBucket: 'dashfleet-app-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASTJ0xf56Hi0IoLHCDCeh4BoI5R7IiNAc',
    appId: '1:992090844900:android:3dad4a2fb570a7b36b46f1',
    messagingSenderId: '992090844900',
    projectId: 'dashfleet-app-flutter',
    storageBucket: 'dashfleet-app-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfawPp6fh7ixrzCDt7ZNf69OZU-Czjgmo',
    appId: '1:992090844900:ios:05478b8987955d5f6b46f1',
    messagingSenderId: '992090844900',
    projectId: 'dashfleet-app-flutter',
    storageBucket: 'dashfleet-app-flutter.appspot.com',
    iosClientId: '992090844900-3q8o5tvdavleds11pnufjrk50tu1t97c.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashfleetAppFlutter',
  );
}
