name: dashfleet_app_flutter
description: A new Flutter project.


publish_to: 'none' 

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.7.1
  get: ^4.6.5
  firebase_auth: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

